name: Push Release to GitLab

on:
  push:
    tags:
      - '*'

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Git
        run: |
          git config --global user.name 'Siddhant Gautam'
          git config --global user.email 'sgautam8434@gmail.com'

      - name: Setup GitLab
        env:
          GITLAB_PAT: glpat-opFVoYHmjqbshYzdZBGr
        run: |
          echo "Setting up GitLab"
          git remote add gitlab https://oauth2:${GITLAB_PAT}@gitlab.com/siddhantgautam/nmit_hack.git

      - name: Push to GitLab Master Branch
        run: |
          echo "Pushing code to GitLab..."
          git push gitlab HEAD:push_to_gitlab --force
          echo "Code has been pushed"

      - name: Extract Tag Name
        id: tag_name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Extracted tag name: $TAG_NAME"
          echo "::set-output name=tag::$TAG_NAME"

      - name: Create and Push Tag to GitLab
        env:
          TAG_NAME: ${{ steps.tag_name.outputs.tag }}
        run: |
          echo "Creating and pushing tag $TAG_NAME to GitLab..."
          git tag -f $TAG_NAME
          git push gitlab $TAG_NAME --force
          echo "Tag $TAG_NAME pushed to GitLab."