name: Push Release to GitLab

on:
  push:
    tags:
      - '*'

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.name 'Siddhant Gautam'
          git config --global user.email 'sgautam8434@gmail.com'
          echo "Git identity set up with name 'Your Name' and email 'your-email@example.com'"

      - name: Determine Branch Name
        id: branch_name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/tags/}"
          echo "Branch name is $BRANCH_NAME"
          echo "::set-output name=branch::$BRANCH_NAME"

      - name: Setup GitLab Remote
        env:
          GITLAB_PAT: glpat-opFVoYHmjqbshYzdZBGr
        run: |
          echo "Setting up GitLab remote..."
          git remote add gitlab https://oauth2:${GITLAB_PAT}@gitlab.com/siddhantgautam/nmit_hack.git
          echo "Remote GitLab repository added"
          
          echo "Pulling latest changes from GitLab..."
          git pull gitlab main
          echo "Latest changes pulled from GitLab"

      - name: Push to GitLab Master Branch
        run: |
          echo "Pushing code to the master branch in GitLab..."
          git push gitlab HEAD:main
          echo "Code has been pushed to the master branch in the GitLab repository."

